version: '3.8'

services:
  app:
    build: .
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - db
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_PORT=${DB_PORT}
      - CRYPTO_SECRET_KEY=${CRYPTO_SECRET_KEY}
      - API_PORT=${API_PORT}
      - LOGLEVEL=${LOGLEVEL}
    restart: always
    networks:
      - my_app_network
      - my_db_network

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE_NAME}
    volumes:
      - ./src/v1/infrastructure/docker/db_volume:/var/lib/mysql
      - ./src/v1/infrastructure/docker/scripts/:/docker-entrypoint-initdb.d/
    ports:
      - '${DB_PORT}:${DB_PORT}'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    networks:
      - my_db_network

networks:
  my_app_network:
    driver: bridge
  my_db_network:
    driver: bridge
