version: "3.8"

services:
  app3:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db3
    environment:
      - DB_DRIVER=postgres
      - DB_HOST=db3
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_DATABASE_NAME=mydbuser
      - DB_PORT=5432
    restart: always

  db3: 
    image: mysql:latest
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DATABASE_NAME=mydbuser
    ports:
      - "5432:5432"
    volumes:
      - ./src/v1/infrastructure/docker/scripts:/tmp
      - ./src/v1/infrastructure/docker/db_storage/:/var/lib/postgresql/data
      - ./src/v1/infrastructure/docker/data/:/docker-entrypoint-initdb.d/
    restart: always

